"""Tests for kindle.stages.package — package_node()."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, call, patch

import pytest

from kindle.agent import AgentResult
from kindle.stages.package import SYSTEM_PROMPT, package_node


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_state(project_dir: str, **overrides) -> dict:
    """Return a minimal KindleState dict for package_node()."""
    state: dict = {
        "project_dir": project_dir,
        "idea": "Build a CLI weather app",
        "feature_spec": {"name": "weather-cli", "features": ["current", "forecast"]},
        "architecture": "Python CLI with Click, requests, Rich",
        "dev_tasks": [
            {"id": 1, "title": "Setup project scaffolding"},
            {"id": 2, "title": "Implement weather API client"},
        ],
    }
    state.update(overrides)
    return state


def _make_agent_result(text: str = "Done") -> AgentResult:
    return AgentResult(
        text=text,
        tool_calls=[],
        raw_messages=[],
        elapsed_seconds=12.3,
        turns_used=5,
    )


def _setup_project_dir(tmp_path: Path) -> Path:
    """Create the minimal on-disk structure that artifacts helpers expect."""
    project_dir = tmp_path / "project"
    (project_dir / "artifacts").mkdir(parents=True)
    (project_dir / "logs").mkdir(parents=True)
    (project_dir / "workspace").mkdir(parents=True)
    # metadata.json is needed by mark_stage_complete / mark_project_done
    meta = {
        "project_id": "kindle_test1234",
        "idea": "test idea",
        "created_at": "2026-01-01T00:00:00+00:00",
        "status": "in_progress",
        "stages_completed": [],
    }
    (project_dir / "metadata.json").write_text(json.dumps(meta))
    return project_dir


# ---------------------------------------------------------------------------
# Tests — happy path
# ---------------------------------------------------------------------------


class TestPackageNodeHappyPath:
    """package_node() with a README generated by the agent."""

    @pytest.fixture()
    def project_dir(self, tmp_path: Path) -> Path:
        return _setup_project_dir(tmp_path)

    @pytest.fixture()
    def ui(self) -> MagicMock:
        return MagicMock()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_returns_package_readme_and_current_stage(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """Return dict must contain the README content and stage name."""
        readme_content = "# Weather CLI\nA simple CLI weather app."
        # Simulate the agent writing README.md into the workspace
        (project_dir / "workspace" / "README.md").write_text(readme_content)
        mock_run_agent.return_value = _make_agent_result()

        result = await package_node(_make_state(str(project_dir)), ui)

        assert result["package_readme"] == readme_content
        assert result["current_stage"] == "package"

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_saves_package_readme_artifact(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """When README.md exists, it must be persisted as package_readme.md artifact."""
        readme_content = "# My Project\nSome docs."
        (project_dir / "workspace" / "README.md").write_text(readme_content)
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        artifact_path = project_dir / "artifacts" / "package_readme.md"
        assert artifact_path.exists()
        assert artifact_path.read_text() == readme_content

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_marks_stage_complete(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """mark_stage_complete must record 'package' in metadata."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        meta = json.loads((project_dir / "metadata.json").read_text())
        assert "package" in meta["stages_completed"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_marks_project_done(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """mark_project_done must set status to 'completed'."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        meta = json.loads((project_dir / "metadata.json").read_text())
        assert meta["status"] == "completed"
        assert "completed_at" in meta

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_ui_lifecycle_calls(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """UI must receive stage_start, deploy_complete, and stage_done."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        ui.stage_start.assert_called_once_with("package")
        ui.deploy_complete.assert_called_once_with(str(project_dir / "workspace"))
        ui.stage_done.assert_called_once_with("package")


# ---------------------------------------------------------------------------
# Tests — run_agent call verification
# ---------------------------------------------------------------------------


class TestPackageNodeAgentCall:
    """Verify that run_agent() is invoked with the correct arguments."""

    @pytest.fixture()
    def project_dir(self, tmp_path: Path) -> Path:
        return _setup_project_dir(tmp_path)

    @pytest.fixture()
    def ui(self) -> MagicMock:
        return MagicMock()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_called_with_correct_workspace_cwd(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """cwd passed to run_agent must point to the workspace directory."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["cwd"] == str(project_dir / "workspace")

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_called_with_persona_and_stage(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """run_agent must receive persona and stage for package."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["persona"] == "Principal DevOps Engineer"
        assert kwargs["stage"] == "package"

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_called_with_system_prompt(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """The module-level SYSTEM_PROMPT must be forwarded to the agent."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["system_prompt"] == SYSTEM_PROMPT

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_user_prompt_contains_project_context(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """The user prompt must embed the idea, feature_spec, architecture, and dev_tasks."""
        state = _make_state(str(project_dir))
        mock_run_agent.return_value = _make_agent_result()

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        prompt = kwargs["user_prompt"]
        # Core context must appear in the prompt
        assert state["idea"] in prompt
        assert json.dumps(state["feature_spec"], indent=2) in prompt
        assert state["architecture"] in prompt
        assert json.dumps(state["dev_tasks"], indent=2) in prompt

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_receives_model_from_state(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """When state contains 'model', it must be forwarded to run_agent."""
        mock_run_agent.return_value = _make_agent_result()
        state = _make_state(str(project_dir), model="claude-sonnet-4-20250514")

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["model"] == "claude-sonnet-4-20250514"

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_receives_max_turns_from_state(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """When state contains 'max_agent_turns', it maps to max_turns kwarg."""
        mock_run_agent.return_value = _make_agent_result()
        state = _make_state(str(project_dir), max_agent_turns=25)

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["max_turns"] == 25

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_default_max_turns(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """Without max_agent_turns in state, default to 50."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["max_turns"] == 50

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_agent_receives_ui_and_project_dir(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """run_agent must receive the UI instance and project_dir."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["ui"] is ui
        assert kwargs["project_dir"] == str(project_dir)


# ---------------------------------------------------------------------------
# Tests — no README generated
# ---------------------------------------------------------------------------


class TestPackageNodeNoReadme:
    """Edge case: agent doesn't create a README.md."""

    @pytest.fixture()
    def project_dir(self, tmp_path: Path) -> Path:
        return _setup_project_dir(tmp_path)

    @pytest.fixture()
    def ui(self) -> MagicMock:
        return MagicMock()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_returns_empty_readme_when_file_missing(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """If README.md is not created, package_readme must be empty string."""
        mock_run_agent.return_value = _make_agent_result()
        # Do NOT create workspace/README.md

        result = await package_node(_make_state(str(project_dir)), ui)

        assert result["package_readme"] == ""
        assert result["current_stage"] == "package"

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_no_artifact_saved_when_readme_missing(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """save_artifact must NOT be called when README is empty."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        artifact_path = project_dir / "artifacts" / "package_readme.md"
        assert not artifact_path.exists()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_stage_still_marked_complete_without_readme(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """Stage and project completion must happen regardless of README."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        meta = json.loads((project_dir / "metadata.json").read_text())
        assert "package" in meta["stages_completed"]
        assert meta["status"] == "completed"


# ---------------------------------------------------------------------------
# Tests — state defaults / missing optional fields
# ---------------------------------------------------------------------------


class TestPackageNodeStateDefaults:
    """Verify graceful handling when optional state keys are absent."""

    @pytest.fixture()
    def project_dir(self, tmp_path: Path) -> Path:
        return _setup_project_dir(tmp_path)

    @pytest.fixture()
    def ui(self) -> MagicMock:
        return MagicMock()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_missing_feature_spec_defaults_to_empty_dict(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """feature_spec defaults to {} when not in state."""
        mock_run_agent.return_value = _make_agent_result()
        state = {"project_dir": str(project_dir)}

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert json.dumps({}, indent=2) in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_missing_architecture_defaults_to_empty_string(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """architecture defaults to '' when not in state."""
        mock_run_agent.return_value = _make_agent_result()
        state = {"project_dir": str(project_dir)}

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert "\nARCHITECTURE:\n" in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_missing_dev_tasks_defaults_to_empty_list(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """dev_tasks defaults to [] when not in state."""
        mock_run_agent.return_value = _make_agent_result()
        state = {"project_dir": str(project_dir)}

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert json.dumps([], indent=2) in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_missing_idea_defaults_to_empty_string(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """idea defaults to '' when not in state."""
        mock_run_agent.return_value = _make_agent_result()
        state = {"project_dir": str(project_dir)}

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert "\nIDEA: " in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_model_none_when_missing_from_state(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """model must be None when not provided in state."""
        mock_run_agent.return_value = _make_agent_result()
        state = {"project_dir": str(project_dir)}

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["model"] is None


# ---------------------------------------------------------------------------
# Tests — prompt structure
# ---------------------------------------------------------------------------


class TestPackageNodePrompt:
    """Verify the user prompt is assembled correctly."""

    @pytest.fixture()
    def project_dir(self, tmp_path: Path) -> Path:
        return _setup_project_dir(tmp_path)

    @pytest.fixture()
    def ui(self) -> MagicMock:
        return MagicMock()

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_prompt_starts_with_package_instruction(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """First line should be the package instruction."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert kwargs["user_prompt"].startswith("Package this project for delivery.")

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_prompt_ends_with_dockerfile_mention(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """Prompt should end with the README/git/Dockerfile instruction."""
        mock_run_agent.return_value = _make_agent_result()

        await package_node(_make_state(str(project_dir)), ui)

        _, kwargs = mock_run_agent.call_args
        assert "optionally add a Dockerfile" in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_prompt_includes_json_serialized_feature_spec(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """feature_spec must be JSON-serialized with indent=2."""
        state = _make_state(str(project_dir))
        mock_run_agent.return_value = _make_agent_result()

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        expected_json = json.dumps(state["feature_spec"], indent=2)
        assert expected_json in kwargs["user_prompt"]

    @patch("kindle.stages.package.run_agent", new_callable=AsyncMock)
    async def test_prompt_includes_json_serialized_dev_tasks(
        self,
        mock_run_agent: AsyncMock,
        project_dir: Path,
        ui: MagicMock,
    ):
        """dev_tasks must be JSON-serialized with indent=2."""
        state = _make_state(str(project_dir))
        mock_run_agent.return_value = _make_agent_result()

        await package_node(state, ui)

        _, kwargs = mock_run_agent.call_args
        expected_json = json.dumps(state["dev_tasks"], indent=2)
        assert expected_json in kwargs["user_prompt"]
